export const AWS_DIAGNOSTIC_CODES = {
  // Catalog & General
  UNKNOWN_RESOURCE: "AWS-CATALOG-UNKNOWN-RESOURCE-001",
  UNKNOWN_RELATIONSHIP: "AWS-RELATIONSHIP-UNKNOWN-KIND-001",

  // Networking & Containment
  RDS_PROXY_NETWORK: "AWS-RDS-PROXY-NETWORK-001",
  SUBNET_CONTAINMENT: "AWS-NETWORKING-SUBNET-CONTAINMENT-001",
  SECURITY_GROUP_PLACEMENT: "AWS-SECURITY-SG-PLACEMENT-001",

  // Compute
  LAMBDA_VPC_PLACEMENT: "AWS-COMPUTE-LAMBDA-VPC-001",

  // Data
  S3_PUBLIC_ACCESS_GUIDANCE: "AWS-DATA-S3-PUBLIC-001",

  // Security
  UNATTACHED_ROLE: "AWS-SECURITY-UNATTACHED-ROLE-001",
} as const;
