export const AWS_DIAGNOSTIC_CODES = {
  // Catalog & General
  UNKNOWN_RESOURCE: "AWS-CATALOG-UNKNOWN-RESOURCE-001",
  UNKNOWN_RELATIONSHIP: "AWS-RELATIONSHIP-UNKNOWN-KIND-001",

  // Networking & Containment
  RDS_PROXY_NETWORK: "AWS-RDS-PROXY-NETWORK-001",
  SUBNET_CONTAINMENT: "AWS-NETWORKING-SUBNET-CONTAINMENT-001",
  SECURITY_GROUP_PLACEMENT: "AWS-SECURITY-SG-PLACEMENT-001",

  // Tier 1: Networking
  NAT_GATEWAY_PLACEMENT: "AWS-NETWORKING-NAT-GATEWAY-PLACEMENT-001",
  IGW_ATTACHMENT: "AWS-NETWORKING-IGW-ATTACHMENT-001",
  TRANSIT_GATEWAY_ROUTES: "AWS-NETWORKING-TGW-ROUTES-001",

  // Compute
  LAMBDA_VPC_PLACEMENT: "AWS-COMPUTE-LAMBDA-VPC-001",

  // Data
  S3_PUBLIC_ACCESS_GUIDANCE: "AWS-DATA-S3-PUBLIC-001",

  // Security
  UNATTACHED_ROLE: "AWS-SECURITY-UNATTACHED-ROLE-001",

  // Tier 2: Integration
  STEP_FUNCTIONS_TARGETS: "AWS-INTEGRATION-STEP-FUNCTIONS-TARGETS-001",
  EVENTBRIDGE_TARGETS: "AWS-INTEGRATION-EVENTBRIDGE-TARGETS-001",

  // Tier 2: Analytics
  KINESIS_FIREHOSE_DESTINATION:
    "AWS-ANALYTICS-KINESIS-FIREHOSE-DESTINATION-001",
  EMR_VPC_PLACEMENT: "AWS-ANALYTICS-EMR-VPC-PLACEMENT-001",

  // Tier 2: AI/ML
  SAGEMAKER_VPC_PLACEMENT: "AWS-AI-ML-SAGEMAKER-VPC-PLACEMENT-001",

  // Tier 2: Storage & Data
  EFS_VPC_PLACEMENT: "AWS-STORAGE-EFS-VPC-PLACEMENT-001",
  AURORA_SUBNET_PLACEMENT: "AWS-DATA-AURORA-SUBNET-PLACEMENT-001",

  // Tier 2: DevTools
  CODEPIPELINE_STAGES: "AWS-DEVTOOLS-CODEPIPELINE-STAGES-001",
} as const;
