export const AWS_DIAGNOSTIC_CODES = {
  UNKNOWN_RESOURCE: "AWS-CATALOG-UNKNOWN-RESOURCE",
  UNKNOWN_RELATIONSHIP: "AWS-RELATIONSHIP-UNKNOWN-KIND",
  RDS_PROXY_NETWORK: "AWS-RDS-PROXY-NETWORK-001",
} as const;
