export const GCP_DIAGNOSTIC_CODES = {
  // Catalog & General
  UNKNOWN_RESOURCE: "GCP-CATALOG-UNKNOWN-RESOURCE-001",

  // Networking & Containment
  SUBNET_CONTAINMENT: "GCP-NETWORKING-SUBNET-CONTAINMENT-001",

  // Data
  CLOUD_SQL_NETWORK: "GCP-DATA-CLOUD-SQL-NETWORK-001",
} as const;
