export const GCP_DIAGNOSTIC_CODES = {
  // Catalog & General
  UNKNOWN_RESOURCE: "GCP-CATALOG-UNKNOWN-RESOURCE-001",

  // Networking & Containment
  SUBNET_CONTAINMENT: "GCP-NETWORKING-SUBNET-CONTAINMENT-001",

  // Tier 1: Networking
  CLOUD_NAT_VPC: "GCP-NETWORKING-NAT-VPC-001",
  ALLOYDB_PSC: "GCP-DATA-ALLOYDB-PSC-001",
  FILESTORE_VPC: "GCP-STORAGE-FILESTORE-VPC-001",

  // Data
  CLOUD_SQL_NETWORK: "GCP-DATA-CLOUD-SQL-NETWORK-001",

  // Tier 2: Integration
  WORKFLOWS_TARGETS: "GCP-INTEGRATION-WORKFLOWS-TARGETS-001",
  EVENTARC_TARGETS: "GCP-INTEGRATION-EVENTARC-TARGETS-001",

  // Tier 2: Analytics
  DATAPROC_VPC_PLACEMENT: "GCP-ANALYTICS-DATAPROC-VPC-PLACEMENT-001",

  // Tier 2: AI/ML
  AI_PLATFORM_VPC_PLACEMENT: "GCP-AI-ML-AI-PLATFORM-VPC-PLACEMENT-001",

  // Tier 2: Identity
  IAP_BACKEND: "GCP-IDENTITY-IAP-BACKEND-001",

  // Tier 2: Containers
  GKE_AUTOPILOT_CONFIG: "GCP-CONTAINERS-GKE-AUTOPILOT-CONFIG-001",

  // Storage
  CLOUD_STORAGE_PUBLIC: "GCP-STORAGE-CLOUD-STORAGE-PUBLIC-001",
} as const;
