export const K8S_DIAGNOSTIC_CODES = {
  // Catalog & General
  UNKNOWN_RESOURCE: "K8S-CATALOG-UNKNOWN-RESOURCE-001",

  // Namespaces & Containment
  WORKLOAD_NAMESPACE_CONTAINMENT: "K8S-NAMESPACE-WORKLOAD-CONTAINMENT-001",
  NAMESPACE_CLUSTER_CONTAINMENT: "K8S-NAMESPACE-CLUSTER-CONTAINMENT-001",

  // Workloads
  UNMANAGED_POD: "K8S-WORKLOAD-POD-MANAGED-001",

  // Networking
  SERVICE_TARGET: "K8S-NETWORKING-SERVICE-TARGET-001",
  INGRESS_TARGET: "K8S-NETWORKING-INGRESS-TARGET-001",

  // Storage
  PVC_UNBOUND: "K8S-STORAGE-PVC-UNBOUND-001",

  // RBAC
  BINDING_SUBJECT: "K8S-RBAC-BINDING-SUBJECT-001",
} as const;
