import type { CdnProviderDefinition } from "@archlex/icons-core";

export const AWS_CDN_PROVIDER: CdnProviderDefinition = {
  provider: "aws",
  baseUrl: "https://unpkg.com/aws-icons@3.3.0/icons/architecture-service",
  allowedHosts: ["unpkg.com"],
  releaseId: "3.3.0",
  fileExtension: ".svg",
  mappings: {
    // Core Compute & Containers
    lambda: "AWSLambda",
    ec2: "AmazonEC2",
    ecs: "AmazonElasticContainerService",
    eks: "AmazonElasticKubernetesService",
    ecr: "AmazonElasticContainerRegistry",
    "ecs-anywhere": "AmazonECSAnywhere",
    fargate: "AWSFargate",
    batch: "AWSBatch",
    lightsail: "AmazonLightsail",
    "elastic-beanstalk": "AWSElasticBeanstalk",
    "app-runner": "AWSAppRunner",
    apprunner: "AWSAppRunner",

    // Networking & Content Delivery
    vpc: "AmazonVirtualPrivateCloud",
    subnet: "AmazonVirtualPrivateCloud",
    "route-table": "AmazonVirtualPrivateCloud",
    "security-group": "AmazonVirtualPrivateCloud",
    "vpc-endpoint-interface": "AmazonVirtualPrivateCloud",
    "vpc-endpoint-gateway": "AmazonVirtualPrivateCloud",
    "nat-gateway": "AmazonVirtualPrivateCloud",
    "internet-gateway": "AmazonVirtualPrivateCloud",
    "elastic-ip": "AmazonVirtualPrivateCloud",
    "transit-gateway": "AWSTransitGateway",
    "direct-connect": "AWSDirectConnect",
    "vpn-gateway": "AWSSitetoSiteVPN",
    "customer-gateway": "AWSSitetoSiteVPN",
    "vpn-connection": "AWSSitetoSiteVPN",
    privatelink: "AWSPrivateLink",
    "network-firewall": "AWSNetworkFirewall",
    "global-accelerator": "AWSGlobalAccelerator",
    cloudfront: "AmazonCloudFront",
    route53: "AmazonRoute53",
    "route53-resolver": "AmazonRoute53",
    "vpc-lattice": "AmazonVPCLattice",
    "api-gateway": "AmazonAPIGateway",
    alb: "ElasticLoadBalancing",
    nlb: "ElasticLoadBalancing",
    "cloud-map": "AWSCloudMap",

    // Storage
    s3: "AmazonSimpleStorageService",
    ebs: "AmazonElasticBlockStore",
    efs: "AmazonEFS",
    "fsx-windows": "AmazonFSxforWFS",
    "fsx-lustre": "AmazonFSxforLustre",
    glacier: "AmazonSimpleStorageServiceGlacier",
    "storage-gateway": "AWSStorageGateway",
    backup: "AWSBackup",

    // Database
    rds: "AmazonRDS",
    "rds-proxy": "AmazonRDS",
    aurora: "AmazonAurora",
    dynamodb: "AmazonDynamoDB",
    elasticache: "AmazonElastiCache",
    neptune: "AmazonNeptune",
    documentdb: "AmazonDocumentDB",
    redshift: "AmazonRedshift",
    timestream: "AmazonTimestream",
    keyspaces: "AmazonKeyspaces",

    // Messaging & Integration
    sqs: "AmazonSimpleQueueService",
    sns: "AmazonSimpleNotificationService",
    ses: "AmazonSimpleEmailService",
    "sns-mobile": "AmazonSimpleNotificationService",
    eventbridge: "AmazonEventBridge",
    "step-functions": "AWSStepFunctions",
    appflow: "AmazonAppFlow",
    appsync: "AWSAppSync",
    mq: "AmazonMQ",
    msk: "AmazonManagedStreamingforApacheKafka",

    // Security, Identity & Compliance
    "iam-role": "AWSIdentityandAccessManagement",
    kms: "AWSKeyManagementService",
    "secrets-manager": "AWSSecretsManager",
    acm: "AWSCertificateManager",
    waf: "AWSWAF",
    shield: "AWSShield",
    guardduty: "AmazonGuardDuty",
    macie: "AmazonMacie",
    inspector: "AmazonInspector",
    detective: "AmazonDetective",
    "audit-manager": "AWSAuditManager",
    artifact: "AWSArtifact",

    // Management & Governance
    "cloudwatch-logs": "AmazonCloudWatch",
    "cloudwatch-metrics": "AmazonCloudWatch",
    "cloudwatch-alarms": "AmazonCloudWatch",
    cloudtrail: "AWSCloudTrail",
    xray: "AWSXRay",
    "systems-manager": "AWSSystemsManager",
    cloudformation: "AWSCloudFormation",
    "service-catalog": "AWSServiceCatalog",
    config: "AWSConfig",
    "control-tower": "AWSControlTower",
    organizations: "AWSOrganizations",
    "compute-optimizer": "AWSComputeOptimizer",
    "cost-explorer": "AWSCostExplorer",
    budgets: "AWSBudgets",
    "savings-plans": "SavingsPlans",
    "managed-grafana": "AmazonManagedGrafana",
    "managed-prometheus": "AmazonManagedServiceforPrometheus",

    // Developer Tools
    codepipeline: "AWSCodePipeline",
    codebuild: "AWSCodeBuild",
    codedeploy: "AWSCodeDeploy",
    codecommit: "AWSCodeCommit",
    codeartifact: "AWSCodeArtifact",
    codeguru: "AmazonCodeGuru",
    cloud9: "AWSCloud9",

    // Analytics
    athena: "AmazonAthena",
    glue: "AWSGlue",
    emr: "AmazonEMR",
    "kinesis-streams": "AmazonKinesisDataStreams",
    "kinesis-firehose": "AmazonDataFirehose",
    "kinesis-video": "AmazonKinesisVideoStreams",
    "kinesis-analytics": "AmazonKinesis",
    "data-pipeline": "AmazonKinesis",
    quicksight: "AmazonQuickSuite",
    opensearch: "AmazonOpenSearchService",

    // Machine Learning & AI
    sagemaker: "AmazonSageMaker",
    bedrock: "AmazonBedrock",
    rekognition: "AmazonRekognition",
    comprehend: "AmazonComprehend",
    translate: "AmazonTranslate",
    polly: "AmazonPolly",
    transcribe: "AmazonTranscribe",
    lex: "AmazonLex",
    kendra: "AmazonKendra",
    forecast: "AmazonForecast",
    personalize: "AmazonPersonalize",

    // Application Integration
    "app-mesh": "AWSAppMesh",
    pinpoint: "AmazonPinpoint",

    // IoT
    "iot-core": "AWSIoTCore",
    "iot-events": "AWSIoTEvents",
    "iot-greengrass": "AWSIoTGreengrass",
    "iot-sitewise": "AWSIoTSiteWise",
    "iot-twinmaker": "AWSIoTTwinMaker",

    // Media Services
    medialive: "AWSElementalMediaLive",
    mediaconvert: "AWSElementalMediaConvert",
    mediapackage: "AWSElementalMediaPackage",
    mediaconnect: "AWSElementalMediaConnect",
    mediatailor: "AWSElementalMediaTailor",
    mediastore: "AWSElementalMediaStore",
    ivs: "AmazonInteractiveVideoService",

    // End User Computing
    workspaces: "AmazonWorkSpaces",
    appstream: "AmazonWorkSpaces",
    workdocs: "AmazonWorkDocs",
    workmail: "AmazonWorkMail",
    connect: "AmazonConnect",
    chime: "AmazonChime",
    wickr: "AWSWickr",

    // Migration & Transfer
    dms: "AWSDatabaseMigrationService",
    datasync: "AWSDataSync",
    "transfer-family": "AWSTransferFamily",
    "migration-hub": "AWSMigrationHub",
    "migration-evaluator": "AWSMigrationEvaluator",
    "application-discovery": "AWSApplicationDiscoveryService",
    "application-migration": "AWSApplicationMigrationService",

    // Infrastructure & Edge
    outposts: "AWSOutpostsfamily",
    "outposts-rack": "AWSOutpostsrack",
    "outposts-server": "AWSOutpostsservers",
    snowball: "AWSSnowball",
    "snowball-edge": "AWSSnowballEdge",
    wavelength: "AWSWavelength",
    "local-zones": "AWSLocalZones",

    // Other Services
    "managed-blockchain": "AmazonManagedBlockchain",
    "ground-station": "AWSGroundStation",
    braket: "AmazonBraket",
    monitron: "AmazonMonitron",
    panorama: "AWSPanorama",
    "supply-chain": "AWSSupplyChain",
    "mainframe-modernization": "AWSMainframeModernization",
    gamelift: "AmazonGameLiftServers",
    opsworks: "AWSCloudFormation",
    "opsworks-stacks": "AWSCloudFormation",
    "opsworks-cm": "AWSCloudFormation",
  },
  attribution: {
    source: "aws-icons npm package",
    license: "Apache-2.0",
    url: "https://www.npmjs.com/package/aws-icons",
  },
  timeoutMs: 10_000,
  maxResponseBytes: 256_000,
};
