import type { CdnProviderDefinition } from "@archlex/icons-core";

export const AWS_CDN_PROVIDER: CdnProviderDefinition = {
  provider: "aws",
  baseUrl: "https://unpkg.com/aws-icons@3.3.0/icons/architecture-service",
  allowedHosts: ["unpkg.com"],
  releaseId: "3.3.0",
  fileExtension: ".svg",
  mappings: {
    lambda: "AWSLambda",
    s3: "AmazonSimpleStorageService",
    "api-gateway": "AmazonAPIGateway",
    cloudfront: "AmazonCloudFront",
    dynamodb: "AmazonDynamoDB",
    ec2: "AmazonEC2",
    ecs: "AmazonElasticContainerService",
    eks: "AmazonElasticKubernetesService",
    elasticache: "AmazonElastiCache",
    eventbridge: "AmazonEventBridge",
    "iam-role": "AWSIdentityandAccessManagement",
    rds: "AmazonRDS",
    "rds-proxy": "AmazonRDS",
    "route-table": "AmazonVirtualPrivateCloud",
    route53: "AmazonRoute53",
    "security-group": "AmazonVirtualPrivateCloud",
    sns: "AmazonSimpleNotificationService",
    sqs: "AmazonSimpleQueueService",
    subnet: "AmazonVirtualPrivateCloud",
    vpc: "AmazonVirtualPrivateCloud",
    apprunner: "AWSAppRunner",
    "app-runner": "AWSAppRunner",
    "step-functions": "AWSStepFunctions",
  },
  attribution: {
    source: "aws-icons npm package",
    license: "Apache-2.0",
    url: "https://www.npmjs.com/package/aws-icons",
  },
  timeoutMs: 10_000,
  maxResponseBytes: 256_000,
};
